### ISSUE TITLE
Upgrading/Migrating from uMarketingSuite

### ISSUE THREAD

**Issue by whitter** [umbraco/Umbraco.Engage.Issues#1]
Hi,

I know we are not on a full release of the Engage product yet.  But I have been playing around with uMarketingSuite for awhile and recently upgraded to Engage.  During the installation of Engage and removal of uMarketingSuite there does not appear to be any automated migration of uMarketingSuite data into the new Engage tables.

Did not bother me in my playground but can imagine it being an issue on live systems.

**Comment by cornehoskam** [comment]
Hi @whitter,

Thank you for playing around with Umbraco Engage. You would be correct in that Engage itself will not automatically upgrade existing installations. When the official release gets out we will be providing the nessecary documentation to migrate & configure Umbraco Engage for existing uMarketingSuite clients! 🙂
