### ISSUE TITLE
Engage Headless Swagger documentation example do not reflect what is actually returned

### ISSUE THREAD

**Issue by whitter** [umbraco/Umbraco.Engage.Issues#2]
Hi,

In playing around with uMarketingSuite/Engage if been getting my head around how to use it in a headless setup.

After upgrading from uMarketingSuite to Engage I've noted an issue with the Swagger documentation that result in tools like hey-api generating incorrect TS models.

For instance the response from `/umbraco/engage/api/v1/segmentation/content/activesegments/{path}` is documented as:

```json
{
  "segmentedContent": [
    {
      "contentTypeAlias": "string",
      "contentId": 0,
      "contentGuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "contentUrls": [
        "string"
      ],
      "segments": [
        {
          "umbracoSegmentAlias": "string",
          "segmentId": 0,
          "segmentName": "string",
          "segmentType": "string",
          "segmentApplicationType": "string"
        }
      ]
    }
  ]
}
```

But the actual response from the API endpoint is:

```json
{
   "contentTypeAlias":"string",
   "contentId":0,
   "contentGuid":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
   "contentUrls":[
      "string"
   ],
   "segments":[
      {
         "umbracoSegmentAlias":"string",
         "segmentId":0,
         "segmentName":"string",
         "segmentType":"string",
         "segmentApplicationType":"string"
      }
   ]
```

---
_This item has been added to our backlog AB#45660_

**Comment by cornehoskam** [comment]
Hi @whitter,

Thank you for reporting this issue, you would be correct!
I have noted the discrepancy and will change the response documentation to match the action response!

**Comment by cornehoskam** [comment]
Hi @whitter,
This issue has been resolved in the first official release version of Umbraco Engage, 13.0.0!
